name: win

on:
  workflow_dispatch:

jobs:
  build_Win_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build --config Release
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ezSqlite_win
        path: bin\ezSqlite*
